include::../attribute.adoc[]

== 概要

本プロジェクトの名称 VT_HP とは Visual Testing for Home Page services の略です。

QUICKは銀行・証券会社を顧客として「ホームページサービス」を提供している。コンサルティング営業本部ネットGがホームページサービスの開発と維持保守を担当している。2020年後半にホームページサービスのシステムの基幹部分を改変する予定がある。Qserach.exeをバージョンアップする。この改変をやり遂げるには、ユーザの視点から画面がどう見えるかの確認を十分に行うことが必要である。たくさんのURLを目で視るだけの作業はひどく退屈だ。誰もやりたくない。でもやらなきゃならない。そこで VT_HP の出番です。VT_HPを使うことによってホームページサービスの画面確認作業を大幅に省力化することができる。

=== ホームページサービスとは具体的にどのURLを指すのか

下記のURLをみよ。このページに列挙されているのが「ホームページサービス」です。

- https://qsup.qhit.net/tl/link/[HP起動リンク https://qsup.qhit.net/tl/link/]

このURLにはBasic認証がかかっているのでID/パスワードを入力せよと要求される。ご存じないなら知っている人に尋ねてください。

=== VT_HPはどういうソフトウェアか

VT_HPはホームページサービスの画面をWebブラウザで開いてキャプチャして画像ファイルにする作業を自動実行することができます。下記の動画をみてください。

* https://drive.google.com/open?id=19w1r1LAhmNMl0GoxfG3_MnYg4luxATY0[VT_HPがFNホームページの画面のキャプチャを撮っている様子]

VT_HPはキャプチャ画像を撮ったあとで吟味もします。ある時点における本番環境とデモ環境とを見比べることができる。あるいは本番環境の入れ替え作業前と後の画像を見比べることができる。見比べた結果をレポートとして出力します。レポートのサンプルがあります。下記のリンクをたどってみてください。

* link:images/index.html[Materials/index.html]





=== VT_HPの効能

HP起動リンク画面に列挙されたURLのなかからサンプルとしてFNホームページサービスをとりあげます。FNホームページサービスのURLはこんな形をしています。

* 本番環境 https://fnhp.qhit.net/fn/fundListOpen.html?corp=qika
* AWSデモ環境 https://ut011.qhit.net/fn/fundListOpen.html?corp=qika

このふたつのURLを見比べましょう。ホスト名が違っています。しかしパスは同じです。パスが同じであるということは、そのURLが要求された時に動くソフトウエアも同一であるはずです。条件がそろえばブラウザに表示される画面も同じになるでしょう。

ほぼ同じタイミングで本番環境とデモ環境とふたつのURLを要求してブラウザ上に表示された画面を見比べたとき、同じ画面が表示がされるでしょうか？これが第一のテストです。

もうひとつ。本番環境でなんらかの変更作業を行う場面を想像してください。プログラムのバージョンアップとか。変更作業の前と後とでもしも画面表示に違いが生じたならばそれを見落とさずに気づきたい。これが第二のテストです。

VT_HPを使うことによってホームページサービスを対象に上記2通りのテストを実行することができます。

VT_HPはブラウザに表示されたWeb画面のスクリーンショットを取得し、PNG画像にしてファイルに保存します。URLのパス部分が同じものどおし、つまり同じ画面の画像ファイルふたつを対にしたものを見比べて画像としての食い違っている部分を検出します。そして画面全体の面積にたいして食い違っている部分の面積が何パーセントを占めるかを数値化します（diff%）。たとえば 0.1% とか、 2.8% とか、 45.7% といった数値が得られます。この数値を手がかりとしてシステムの状態を知ることができます。dffが0.1%ならばふたつの画面はほとんど同一だったといえます。2.8%ならば画面のなかのどの部分に変化があったかを人は調べるべきでしょう。ドル円為替レートのように秒単位で変化する情報がWeb画面のなかに配置されていればこのぐらいのdiff%はあってもおかしくないでしょう。しかし45.7%という数字は大きすぎる。なんらかの不具合があることを示唆する数字です。しかしdiff%が大きいということはどこかがおかしいと気づかせてくれるだけで、どこに問題があるのかは教えてくれません。そこからがテスト担当者の出番です。

VT_HPが数十分走行している間、テスト担当者はほかの仕事をすればいい。あるいはコーヒーを飲んで待っているのもいいですね。VT_HPが完了して異常なしと知らせてくれればテスト担当者は安んじて帰宅することができる。VT_HPがこのURLに異常ありと知らせてくる場合もあるでしょう。テスト担当者は特定されたURLだけに注目すればいい。PNG画像をみれば画面のどこに食い違いがあったかがわかるから、そこにただちに注意を向けることができる。問題の在りかを探し回る手間をVT_HPは省いてくれます。

















下記の動画をご覧ください。


https://drive.google.com/file/d/19w1r1LAhmNMl0GoxfG3_MnYg4luxATY0/view?usp=sharing




